---

moodlebox_install_packages:
  - iptables-persistent
  - hostapd
  - dnsmasq
  - git
  - ntfs-3g
  - exfat-fuse
  - lockfile-progs
  - incron
  - nginx
  - ghostscript
  - php7.3-fpm
  - php7.3-cli
  - php7.3-common
  - php7.3-json
  - php7.3-mbstring
  - php7.3-opcache
  - php7.3-readline
  - php7.3-xmlrpc
  - php7.3-curl
  - php7.3-gd
  - php7.3-intl
  - php7.3-soap
  - php7.3-mysql
  - php7.3-xml
  - php7.3-zip
  - php7.3
  - php-apcu
