---

packages_to_install:
  - git
  - ntfs-3g
  - exfat-fuse
  - udevil
  - direvent
  - nginx
  - ghostscript
  - redis
  - poppler-utils
  - iptables
  - php8.2-fpm
  - php8.2-mbstring
  - php8.2-curl
  - php8.2-gd
  - php8.2-intl
  - php8.2-soap
  - php8.2-mysql
  - php8.2-xml
  - php8.2-zip
  - php8.2-apcu
  - php8.2-tidy
  - php8.2
  - php-apcu
  - php-redis
