---

- name: configure dhcpcd with static IP address {{ moodlebox_ip_address | ipaddr('host') }}
  blockinfile:
    path: '/etc/dhcpcd.conf'
    block: |
      interface wlan0
      static ip_address={{ moodlebox_ip_address | ipaddr('host') }}
      nohook wpa_supplicant
  notify: restart networking

- name: update access point configuration file
  template:
    src: 'etc/hostapd/hostapd.conf.j2'
    dest: '/etc/hostapd/hostapd.conf'
    mode: '0664'
  notify: restart networking

- name: update access point settings
  lineinfile:
    path: '/etc/default/hostapd'
    regexp: '^#?DAEMON_CONF'
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: restart networking

- name: unmask, enable and start hostapd
  systemd:
    name: 'hostapd'
    state: 'started'
    enabled: 'yes'
    masked: 'no'

- name: update dnsmasq configuration
  template:
    src: 'etc/dnsmasq.conf.j2'
    dest: '/etc/dnsmasq.conf'
    mode: '0664'
  notify: restart networking

- name: update dnsmasq service file
  blockinfile:
    path: '/lib/systemd/system/dnsmasq.service'
    insertbefore: '^\[Install\]\s*$'
    block: |
      RestartSec=5
      Restart=on-failure
  notify: restart networking

- meta: flush_handlers
