---

- name: backup default wireless chip firmware
  copy:
    src: '/lib/firmware/brcm/{{ item }}'
    dest: '/lib/firmware/brcm/{{ item }}.{{ ansible_date_time.date }}'
    mode: 'preserve'
    remote_src: 'yes'
    force: 'no'
  with_items:
    - brcmfmac43455-sdio.bin

- name: replace wireless chip firmware with minimal one
  copy:
    src: 'lib/firmware/brcm/{{ item.src }}'
    dest: '/lib/firmware/brcm/{{ item.dest }}'
    mode: 0644
  with_items:
    - { src: '4th_trial_minimal_43455_fw.bin', dest: 'brcmfmac43455-sdio.bin' }
  register: new_wifi_firmware
  notify: reboot box

- name: prevent overwriting minimal firmware by apt update
  dpkg_selections:
    name: 'firmware-brcm80211'
    selection: hold

- name: flush handlers
  meta: flush_handlers
