---

- name: configure dhcpcd
  blockinfile:
    path: '/etc/dhcpcd.conf'
    block: |
      interface wlan0
      static ip_address={{ moodlebox_ip_address | ipaddr('host') }}
  notify: restart networking

- name: update access point configuration file
  template:
    src: 'etc/hostapd/hostapd.conf.j2'
    dest: '/etc/hostapd/hostapd.conf'
  notify: restart networking

- name: update access point settings
  lineinfile:
    path: '/etc/default/hostapd'
    regexp: '^#?DAEMON_CONF'
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: restart networking

- name: update dnsmasq configuration
  template:
    src: 'etc/dnsmasq.conf.j2'
    dest: '/etc/dnsmasq.conf'
  notify: restart networking

- name: update dnsmasq service file
  blockinfile:
    path: '/lib/systemd/system/dnsmasq.service'
    insertbefore: '^\[Install\]\s*$'
    block: |
      RestartSec=5
      Restart=on-failure
  notify: restart networking

- name: configure IP forwarding
  import_tasks: iproute.yml
  notify: restart networking

- name: configure zeroconf service
  template:
    src: 'etc/avahi/services/moodlebox.service.j2'
    dest: '/etc/avahi/services/{{ moodlebox_hostname }}.service'
  notify: restart networking

- name: configure nginx
  template:
    src: 'etc/nginx/sites-available/default.j2'
    dest: '/etc/nginx/sites-available/default'
  notify: restart web services

- meta: flush_handlers
