---

- name: get MoodleBox plugin version '{{ moodlebox_moodlebox_plugin_version }}' from git repository
  git:
    repo: 'https://github.com/moodlebox/moodle-tool_moodlebox.git'
    dest: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox'
    version: '{{ moodlebox_moodlebox_plugin_version }}'
    depth: 1

- name: touch files for MoodleBox plugin functionality
  file:
    path: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox/{{ item }}'
    state: 'touch'
  with_items:
    - '.reboot-server'
    - '.shutdown-server'
    - '.set-server-datetime'
    - '.newpassword'
    - '.wifisettings'
    - '.resize-partition'

- name: change MoodleBox plugin file permissions (1)
  file:
    path: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox'
    state: 'directory'
    owner: '{{ moodlebox_username }}'
    group: 'www-data'
    mode: 'ug+w,o-w'
    recurse: 'yes'

- name: change MoodleBox plugin file permissions (2)
  file:
    path: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox/bin'
    state: 'directory'
    mode: 0754
    recurse: 'yes'

- name: create sudoers file for MoodleBox plugin usage
  copy:
    src: 'etc/sudoers.d/020_www-data-nopasswd'
    dest: '/etc/sudoers.d/020_www-data-nopasswd'
    mode: '0440'
    validate: 'visudo -cf %s'

- name: install MoodleBox plugin via CLI
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/upgrade.php"
    --allow-unstable
    --non-interactive'
  args:
    chdir: '{{ moodlebox_moodle_source_dir }}'
  register: moodlebox_plugin_installed
  changed_when: moodlebox_plugin_installed.rc == 0
