moodlebox_install_packages:
  - iptables-persistent
  - hostapd
  - dnsmasq
  - git
  - ntfs-3g
  - exfat-fuse
  - lockfile-progs
  - incron
  - nginx
  - ghostscript
  - php7.0-fpm
  - php7.0-cli
  - php7.0-common
  - php7.0-json
  - php7.0-mbstring
  - php7.0-opcache
  - php7.0-readline
  - php7.0-xmlrpc
  - php7.0-curl
  - php7.0-gd
  - php7.0-intl
  - php7.0-soap
  - php7.0-mysql
  - php7.0-mcrypt
  - php7.0-xml
  - php7.0-zip
  - php7.0
  - php-apcu
