---

- name: install and configure database server
  import_tasks: db.yml

- name: install/upgrade standard packages and remove useless ones
  import_tasks: packages.yml

- name: install packages needing special care
  import_tasks: specific-packages.yml

- name: misc system configuration
  import_tasks: system.yml

- meta: flush_handlers
