---

- name: set IP forwarding on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: 'true'
    state: present
    reload: 'true'

- name: set iptables persistent rules
  template:
    src: 'etc/iptables/rules.v4.j2'
    dest: '/etc/iptables/rules.v4'
    mode: '0644'
  notify: restart networking

- meta: flush_handlers
